package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserDo;

public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Thu Jan 03 17:39:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Thu Jan 03 17:39:05 CST 2019
     */
    int insert(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Thu Jan 03 17:39:05 CST 2019
     */
    int insertSelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Thu Jan 03 17:39:05 CST 2019
     */
    UserDo selectByPrimaryKey(Integer id);


    UserDo selectByTelphone(String telphone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Thu Jan 03 17:39:05 CST 2019
     */
    int updateByPrimaryKeySelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Thu Jan 03 17:39:05 CST 2019
     */
    int updateByPrimaryKey(UserDo record);
}