package com.miaoshaproject.dataobject;

public class SequenceDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.curr_value
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    private Integer currValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    private Short step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.curr_value
     *
     * @return the value of sequence_info.curr_value
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    public Integer getCurrValue() {
        return currValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.curr_value
     *
     * @param currValue the value for sequence_info.curr_value
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    public void setCurrValue(Integer currValue) {
        this.currValue = currValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    public Short getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Sun Jan 13 19:55:43 CST 2019
     */
    public void setStep(Short step) {
        this.step = step;
    }
}